apiVersion: v1
appVersion: 2.13.20
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: dex
sources:
- https://github.com/jenkins-x/dex.git
version: 2.13.20
